### ISSUE TITLE
QUIC MVP

### ISSUE THREAD

**Issue by arapov** [openssl/project#1]
```[tasklist]
- [ ] openssl/openssl#20061
- [ ] #26
- [ ] #29
- [ ] #24
- [ ] openssl/openssl#19769
- [ ] openssl/openssl#21029
- [ ] https://github.com/openssl/project/issues/28
- [ ] https://github.com/openssl/project/issues/32
- [ ] https://github.com/openssl/project/issues/33
- [ ] https://github.com/openssl/project/issues/34
- [ ] https://github.com/openssl/project/issues/42
- [ ] https://github.com/openssl/project/issues/58
- [ ] openssl/openssl#21337
- [ ] https://github.com/openssl/project/issues/35
- [ ] openssl/openssl#21547
- [ ] openssl/openssl#21165
- [ ] https://github.com/openssl/project/issues/39
- [ ] https://github.com/openssl/project/issues/114
- [ ] https://github.com/openssl/project/issues/108
- [ ] https://github.com/openssl/project/issues/13
- [ ] #27
- [ ] https://github.com/openssl/project/issues/70
- [ ] https://github.com/openssl/project/issues/74
- [ ] https://github.com/openssl/project/issues/40
- [ ] https://github.com/openssl/project/issues/75
- [ ] https://github.com/openssl/project/issues/76
- [ ] https://github.com/openssl/project/issues/82
- [ ] https://github.com/openssl/project/issues/77
- [ ] https://github.com/openssl/project/issues/78
- [ ] https://github.com/openssl/project/issues/80
- [ ] https://github.com/openssl/project/issues/81
- [ ] https://github.com/openssl/project/issues/85
- [ ] https://github.com/openssl/project/issues/86
- [ ] https://github.com/openssl/project/issues/88
- [ ] https://github.com/openssl/project/issues/91
- [ ] https://github.com/openssl/project/issues/121
- [ ] https://github.com/openssl/project/issues/139
- [ ] https://github.com/openssl/project/issues/142
- [ ] https://github.com/openssl/project/issues/159
- [ ] https://github.com/openssl/project/issues/169
- [ ] https://github.com/openssl/project/issues/83
- [ ] https://github.com/openssl/project/issues/90
- [ ] https://github.com/openssl/project/issues/84
- [ ] https://github.com/openssl/project/issues/87
- [ ] https://github.com/openssl/project/issues/79
- [ ] https://github.com/openssl/project/issues/89
- [ ] https://github.com/openssl/project/issues/92
- [ ] openssl/openssl#22336
- [ ] https://github.com/openssl/project/issues/132
- [ ] https://github.com/openssl/project/issues/251
- [ ] https://github.com/openssl/project/issues/41
- [ ] openssl/openssl#21935
- [ ] https://github.com/openssl/project/issues/254
- [ ] https://github.com/openssl/project/issues/236
- [ ] openssl/openssl#22394
- [ ] openssl/openssl#22368
- [ ] https://github.com/openssl/project/issues/207
- [ ] openssl/openssl#22436
- [ ] openssl/openssl#22439
- [ ] openssl/openssl#22424
- [ ] openssl/openssl#22348
- [ ] https://github.com/openssl/project/issues/250
- [ ] https://github.com/openssl/project/issues/252
- [ ] https://github.com/openssl/project/issues/253
- [ ] openssl/openssl#22523
- [ ] https://github.com/openssl/project/issues/93
```

**Comment by hlandau** [comment]
I guess this can be closed now! :tada:

**Comment by arapov** [comment]
It is!
