### ISSUE TITLE
Switch utf-16 conversion build time config option to always enabled

### ISSUE THREAD

**Issue by nhorman** [openssl/project#1003]
openssl/project#1029 create a build time config option to always do utf-16 conversion.

In this issue, switch the sense of that option to be default enabled from default disabled

Currently we only do utf-8 => 16 conversion in win32_utf8argv if the OPENSSL_WIN32_UTF8 is set at run time.  According to the security report in vince, the agreed goal was to move this to a build time config variable so that users didn't have to remember to set the env var for each run.  However doing so may create compatibility issues, meaning what we want to do is:
- Create a build time variable that is defaulted to off in our next minor release, allowing customers to enable it, and always do utf-8 = > 16 conversion regardless of the OPENSSL_WIN32_UTF8 variable setting
- Switch the default of the build time variable to be default on in our next major release, so that there is no longer a run time choice in the matter, also allowing for the removal of the environment variable.

Task list here is pretty straightforward I think:

```[tasklist]
### Tasks
- [ ] Confirm that GetCommandLineW always returns the write UTF-16 encoding to the caller in win32_utf8_argv
- [ ] Create a build time variable defaulted to off (named enable-win-utf8 or some such)
- [ ] In win32_utf8argv(), add a check for the associated macro created by the above build time variable.  If set, skip the GetEnvironmentVariableW check in this function, such that we always do utf8 conversion
- [ ] Add a windows only test to ensure that utf8 command line inputs get properly converted to  utf-16
- [ ] Create a subsequent issue targeted for 4.0 to switch the build time setting to default-on, and eliminate the OPENSSL_WIN32_UTF8 environment variable and associated documentation
- [ ] Add tests to check various utf8/utf16 combinations
```

**Comment by levitte** [comment]
Duplicate of openssl/project#1029

**Comment by Sashan** [comment]
If I understand windows documentation right this is perhaps the behavior which should be good for everybody:
  - use [GetCommandLineW()](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinew) to obtain command line args
  - pass the result to  [CommandLineToArgvW()](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw), it returns `LPWSTR` which is utf-16
  - the result of `CommandLineToArgvW()` will be passed to [WideCharToMultiByte()](https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte) and ask the function to give us an utf-8 string.

The hardest part here is to figure out the arguments for `WideCharToMultiByte()` the arguments I'm most concern of:
  - `dwFlags` which as I understand controls behavior of the function for edge cases. those flag can lead potential to the most disruptive behavior as may refuse (error out) on input we currently accept
  - `lpDefaultChar` if there is no valid conversion mapping to utf-8, the missing character will be replaced by `lpDefaultChar`, I' proposing to a '?' here.

**Comment by levitte** [comment]
> The hardest part here is to figure out the arguments for `WideCharToMultiByte()` the arguments I'm most concern of:

Actually, people before us have it already figured out, it's there in existing code.

> * `dwFlags` which as I understand controls behavior of the function for edge cases. those flag can lead potential to the most disruptive behavior as may refuse (error out) on input we currently accept
> 
> * `lpDefaultChar` if there is no valid conversion mapping to utf-8, the missing character will be replaced by `lpDefaultChar`, I' proposing to a '?' here.

Both are answered in https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte:

- dwFlags:

  > **Note**  For the code page 65001 (UTF-8) or the code page 54936 (GB18030, Windows Vista and later), dwFlags must be set to either 0 or WC_ERR_INVALID_CHARS. Otherwise, the function fails with ERROR_INVALID_FLAGS.

  we use 0 (zero) here.

- lpDefaultChar

  > For the CP_UTF7 and CP_UTF8 settings for *CodePage*, this parameter must be set to **NULL**. Otherwise, the function fails with ERROR_INVALID_PARAMETER.

**Comment by Sashan** [comment]
I've submitted draft [PR](https://github.com/openssl/openssl/pull/25934) which follows what Richart proposes.
