### ISSUE TITLE
Windows Binaries

### ISSUE THREAD

**Issue by arapov** [openssl/project#129]
We must create Windows binaries to enhance our software distribution and user experience. It's important to have a user-friendly installer package for these binaries. This will streamline the installation process for our Windows users, which is one of their most frequent requests.

```[tasklist]
### Tasks
- [x] Discuss at the backlog refinement meeting
- [ ] https://github.com/openssl/project/issues/20
- [ ] https://github.com/openssl/project/issues/534
- [ ] openssl/installer#3
- [ ] https://github.com/openssl/project/issues/550
- [ ] https://github.com/openssl/project/issues/551
```
