### ISSUE TITLE
QUIC: Change multistream test to use a dgram_pair

### ISSUE THREAD

**Issue by hlandau** [openssl/project#168]
We have a lot of stochastic test failures in quic_multistream_test. This is largely due to variations in the behaviour of loopback interface latency on various OSes. MacOS in particular seems to have unusually high latency on loopback interfaces.

Since we already test use of QUIC with real sockets in other tests, such as quicapitest, we don't actually need to use real sockets here. So we should change this to use BIO_dgram_pair to make the test more reliable.

Arguably there is an underlying issue here that our multistream test code should be more reliable in the face of varied timing. However random OS variation is not really a great way to shake this sort of thing out, since it is hard to reproduce CI failures and some CI failures have not yet been successfully reproduced.

In future I want to have a diagnostic BIO which can delay, reorder and drop datagrams arbitrarily on command, which should allow us to shake out these kinds of issues in our test code in a way we actually can reproduce and fix.
```[tasklist]
### Tasks
- [ ] identify test cases which can be easily converted to use  a dgram pair
- [ ] convert those test cases
- [ ] figure out what to do with the rest
```
