### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by arapov** [openssl/project#185]
We need to have a plan for further improvements in v3 performance.

re: https://github.com/openssl/openssl/issues/20286 https://github.com/openssl/openssl/issues/17064 https://github.com/openssl/openssl/issues/17627

```[tasklist]
### Tasks
- [ ] https://github.com/openssl/project/issues/453
- [ ] https://github.com/openssl/project/issues/353
- [ ] https://github.com/openssl/project/issues/569
- [ ] https://github.com/openssl/project/issues/566
- [ ] https://github.com/openssl/project/issues/358
- [ ] https://github.com/openssl/project/issues/354
- [ ] https://github.com/openssl/project/issues/441
- [ ] https://github.com/openssl/project/issues/214
- [ ] https://github.com/openssl/project/issues/100
- [ ] https://github.com/openssl/project/issues/357
- [ ] https://github.com/openssl/project/issues/356
- [ ] https://github.com/openssl/project/issues/102
- [ ] https://github.com/openssl/project/issues/54
- [ ] https://github.com/openssl/project/issues/359
- [ ] openssl/openssl#22729
- [ ] openssl/openssl#21833
- [ ] https://github.com/openssl/project/issues/571
- [ ] https://github.com/openssl/project/issues/572
- [ ] https://github.com/openssl/project/issues/573
```

**Comment by mattcaswell** [comment]
Also see the proposal from Nico in openssl/openssl#20715

**Comment by mattcaswell** [comment]
Came in privately: a description of a performance issue calling Python's "load_default_certs" function shows possible performance degradation from multiple threads. Possibly a locking issue?

**Comment by nhorman** [comment]
Note: In reviewing these performance issues, I feel like we need to take a pause on some of them, until such time as we've resolved our performance measurement suite.  I've prioritized those tasks for refinement and execution so that we can have a more clear view of what our performance was on older implementations vs newer so that we can effectively prioritize the remaining tasks here

**Comment by quarckster** [comment]
> Note: In reviewing these performance issues, I feel like we need to take a pause on some of them, until such time as we've resolved our performance measurement suite. I've prioritized those tasks for refinement and execution so that we can have a more clear view of what our performance was on older implementations vs newer so that we can effectively prioritize the remaining tasks here

I believe the performance measurement suite is ready at least for the internal evaluation. The automation runs benchmarks on nightly basis and gather results into the DB. The results are represented as time series charts in a Grafana dashboard.
