### ISSUE TITLE
Beta release checklist && OTC approval

### ISSUE THREAD

**Issue by arapov** [openssl/project#236]
It is required to go through the [beta readiness checklist](https://www.openssl.org/policies/technical/release-requirements.html) and identify and create tickets for the work that must be done before the v3.2 release. Also, have a discussion at OTC about the items that represent issues that might be addressed after the release, in case there are any.

**Comment by paulidale** [comment]
- [ ] The code is functionally complete in regards to the particular release objectives as set by OMC and OTC.
- [ ] There is no remaining refactoring required by OMC or OTC for the release.
- [ ] There are no remaining API changes required for the release.
- [ ] There are no remaining API additions required for the release.
- [ ] All issues triaged as regressions on the development branch from which the release is to be done must have a milestone assigned.
  - Add appropriate triage tag
  - Add appropriate branch tag (if obvious enough)
  - Add milestone (if relevant)
  - Close (if possible)
  - For beta-1: it is since the beginning of development of the current version (i.e. branch point).  For issues which are already triaged, only bugs without the current version and a set milestone need to be looked at.  
- [ ] All issues or pull requests with the milestone for the beta release are closed.
- [ ] There are no outstanding untriaged Coverity issues.
  - Assign severity on Coverity
  - Raise issue (if required)
  - Resolve on Coverity (if possible)
- [ ] Coveralls coverage has not decreased overall from the previous release.
- [ ] The CI must pass on the tip of the development branch before the release commits are added to the tree, including the daily CI builds.
- [ ] The tree must be frozen for at least 3 business days. No changes apart from regression or security fixes should be merged during the freeze.
- [ ] For 2 days before the release there should be no changes to ensure the daily CI builds run on the development tree tip.
- [ ] A passing OTC ready for beta vote.

Earlier lists also included:

- [ ] Confirm that all new public functions and macros are documented.
  - Check missingcrypto.txt for erroneous entries.
- [ ] Check that new exported symbols (in the static build) are named correctly (ossl_ prefix).
- [ ] Builds and passes tests on all primary, secondary and FIPS platforms.
- [ ] All beta milestone items addressed.

**Comment by t8m** [comment]
Coverity: We have fixes for two of the outstanding issues and I've dismissed the remaining two as they are false positives.

**Comment by t8m** [comment]
There are no new missingcrypto.txt entries.

**Comment by t8m** [comment]
I've checked the additions of internal symbols in the .a libraries. There are quite many new symbols added that do not have the ossl_ prefix both in libcrypto.a and libssl.a when compared to 3.1 version. On the other hand all of these use existing prefixes such as tls_ aes_ or similar. It is less than perfect but IMO acceptable. Renaming these would be a huge effort.

**Comment by t8m** [comment]
OTC passed ready to release the beta vote with an exemption for the 2 days waiting period to be just 1 day for this release.
