### ISSUE TITLE
Eliminate use of atexit

### ISSUE THREAD

**Issue by hlandau** [openssl/project#271]
```[tasklist]
### Tasks
- [ ] Produce writeup enumerating the various options for eliminating use of atexit, including long-term options, including pros and cons of each
- [ ] OTC discussion to consider the various options and choose one
- [ ] Implement the chosen strategy
```

**Comment by beldmit** [comment]
Probably it's worth writing a blog post about it

**Comment by paulidale** [comment]
> Probably it's worth writing a blog post about it

Once a decision is made, this is mandatory IMO.

**Comment by Sashan** [comment]
we can close this issue now, as PR [#29385](https://github.com/openssl/openssl/pull/29385)

**Comment by romen** [comment]
@openssl/committers could you point where is the documentation for the communities about this change? I was expecting a design document stating goals and non-goals, explored alternatives and final decision after comparing pros/cons against the design goals.

**Comment by romen** [comment]
As a TAC member I can report that it goes against our openness and transparency goals the fact that the issues do not get updated until their resolution is a fait-accompli .

There wasn’t really much room for the communities to get informed or involved.

**Comment by Sashan** [comment]
the atexit removal is covered here https://github.com/openssl/project/issues/1719

I was not aware #271 exists until today morning. so Ive decided to close it as done.
