### ISSUE TITLE
QUIC MFA

### ISSUE THREAD

**Issue by hlandau** [openssl/project#409]
"QUIC Minor Feature Additions" is a feature package for QUIC which we can hopefully deliver rapidly. It primarily focuses on use cases which have been reported by the community, and is thus targeted at real issues posed by users at this time.

```[tasklist]
### Tasks
- [ ] https://github.com/openssl/project/issues/53
- [ ] https://github.com/openssl/project/issues/410
- [ ] https://github.com/openssl/project/issues/418
- [ ] https://github.com/openssl/project/issues/415
- [ ] https://github.com/openssl/project/issues/412
- [ ] https://github.com/openssl/project/issues/450
- [ ] https://github.com/openssl/project/issues/451
- [ ] https://github.com/openssl/project/issues/411
- [ ] https://github.com/openssl/project/issues/413
- [ ] https://github.com/openssl/openssl/pull/23598#pullrequestreview-1882198545
```

```[tasklist]
### Dropped items
- [ ] https://github.com/openssl/project/issues/416
- [ ] https://github.com/openssl/project/issues/417
```

**Comment by hlandau** [comment]
Based on input from https://github.com/openssl/openssl/discussions/23339

**Comment by arapov** [comment]
Thank you, @hlandau !

**Comment by mattcaswell** [comment]
I wonder whether "Provide way to query/control idle timeout" can be generalised to querying information about the transport parameters.

**Comment by hlandau** [comment]
> I wonder whether "Provide way to query/control idle timeout" can be generalised to querying information about the transport parameters.

Hmmmmmmmm.... it sort of makes sense, but I think it gets into some weeds. A transport parameter is just a TLV &mdash; it doesn't have any defined negotiation semantics, which have to be defined by a particular extension. So it doesn't necessarily make sense to use the IANA Transport Parameter ID namespace as a key for an API which queries "negotiated features", since the transport parameter &mdash; negotiated feature mapping isn't 1:1. Many transport parameters also govern things that can change subsequently (like initial flow control credit).

In actuality the way idle timeout is negotiated using transport parameters is quite unique &mdash; with it being the minimum of the values specified by both endpoints, or disabled entirely if neither specifies a value. That's not really something you see for any other transport parameter currently.

What is definitely true is that we will need an API for controlling feature negotiation in future, and determining what features were negotiated. See all the QUIC extensions for examples. Various options present themselves here... in the past for TLS we've used a set of bitflags (TLS compatibility options etc.) or SSL_ctrl leaf functions.

The question is probably whether there is enough of a common pattern around feature negotiation to justify an API in its own right and not using SSL_ctrls. I suspect there may be, as every feature negotiation involves multiple sets of values:

- what we *requested*
- what the peer *requested*
- what we *got* (the synthesis of the two)

The "data type" being negotiated (e.g. integer values) is another question. I suspect we only really need integers (/booleans) for now.

So abstractly the API we need looks something like:

- get feature (requested) option
- set feature (requested) option
- get feature (peer requested) option
- get feature (negotiated) option

First sketch:

```c
/* What feature value are we locally requesting? */
#define SSL_FEATURE_KIND_REQUEST           0
/* What feature value did the peer request? */
#define SSL_FEATURE_KIND_PEER_REQUEST  1
/* What is the actually negotiated feature value? */
#define SSL_FEATURE_KIND_NEGOTIATED     2

#define SSL_FEATURE_IDLE_TIMEOUT  1
#define SSL_FEATURE_MAX_INITIAL_STREAMS_BIDI   2
#define SSL_FEATURE_MAX_DATAGRAM_SIZE    3
/* and so on */

int SSL_get_feature_int(SSL *s, uint32_t kind, uint32_t feat, uint64_t *v);

/*
 * fails after handshake is complete for things which can only be
 * negotiated via transport parameters; QUIC extensions which define
 * post-handshake ways to change feature values could support this API
 * after handshake however
 */
int SSL_set_feature_int(SSL *s, uint32_t kind, uint32_t feat, uint64_t *v);
```

Thoughts?

**Comment by mattcaswell** [comment]
Yes, something like this looks plausible

**Comment by hlandau** [comment]
Added #450, #451

**Comment by hlandau** [comment]
This epic is now completed.
