### ISSUE TITLE
Propose API deprecations for 3.3

### ISSUE THREAD

**Issue by hlandau** [openssl/project#432]
We should think if there are any APIs we want to deprecate for 3.3.

e.g. are there APIs people would like to be able to drop for 4.0?
```[tasklist]
### Tasks
- [ ] Consider deprecating public mutex API (Hugo)
- [ ] Consider deprecating public atomics API (Hugo)
- [ ] Consider deprecating public thread locals API (Hugo)
- [ ] Consider deprecating openssl/hmac.h:HMAC (Hugo)
- [ ] Consider deprecating openssl/modes.h:* (Hugo)
- [ ] Consider deprecating openssl/ssl2.h (Hugo)
```

**Comment by hlandau** [comment]
Please assign yourself to this item if you would like to spend some time suggesting APIs we might want to deprecate.

**Comment by hlandau** [comment]
If you want to propose deprecating an API, I suggest creating an issue in openssl/openssl and linking it from here.
