### ISSUE TITLE
Develop a benchmark suite

### ISSUE THREAD

**Issue by hlandau** [openssl/project#453]
```[tasklist]
### Tasks
- [ ] https://github.com/openssl/project/issues/454
- [ ] https://github.com/openssl/project/issues/455
- [ ] https://github.com/openssl/project/issues/456
- [ ] https://github.com/openssl/project/issues/457
```

To be based on community reports of performance issues.

This issue does *not* include performance measurements infrastructure, it is just to have a suite of benchmarks that developers can run locally to characterise performance and which are representative of the performance issues which have been reported.

```[tasklist]
### Inputs
- [ ] https://github.com/openssl/openssl/issues/21833
- [ ] https://github.com/openssl/openssl/issues/20286
```
(add input issue links here)

**Comment by nhorman** [comment]
completed
