### ISSUE TITLE
Create NSIS windows installer binary

### ISSUE THREAD

**Issue by nhorman** [openssl/project#534]
Write a windows binary installer using open source NSIS tool and commit to a new installer repository:

```[tasklist]
### Tasks
- [x] Installer should hold both 32 and 64 bit openssl binaries
- [x] Installer should allows installation target to be selected
- [x] Installer should present user with Apache license to accept
- [x] Installer should create registry keys to record per-installation location of default paths that are set at build time in non-windows openssl binaries
- [x] Installer should write uninstaller to install path
```

**Comment by nhorman** [comment]
I've moved the windows installer PR to be part of the installer repo
