### ISSUE TITLE
QUIC Protocol Performance Tuning

### ISSUE THREAD

**Issue by hlandau** [openssl/project#54]
Research task which will generate implementation tasks.
```[tasklist]
### Tasks
- [ ] Measure performance, including relative to & when talking to other libraries
- [ ] Measure performance under a variety of realistic induced network throughput/latency/jitter/loss conditions, compare other impls
- [ ] Observe, track, record packet generation and suboptimalities
- [ ] Observe, track, record ACKM performance & suboptimality
- [ ] Generate issues to rectify identified suboptimalities
```
