### ISSUE TITLE
Implement ECH design doc

### ISSUE THREAD

**Issue by nhorman** [openssl/project#570]
Tracks the implementation of Encrypted Client Hello support (as defined by the design doc [here](https://github.com/openssl/openssl/pull/20408).  Each task below should be thought of as fitting into a sprint.  When ready they will be converted into an issue for scheduling. Preliminary breakdown of future *bite-size* feature-branch PRs. Will likely change as review progresses.

- [ ] complete review of ECH design doc [issue](https://github.com/openssl/openssl/pull/20408).  This is a preliminary review. The rest of the documentation and the implementation are a separate PR that will turn into a feature branch, and will be merged incrementally.
- [ ] Merge final design and API docs into new feature branch.
- [ ] Add feature flag to enable ECH in build
- [ ] Merge ECH headers
- [ ] Merge MVP server side API
- [ ] Add support for HRR
- [ ] Merge MVP client side api
- [ ] Implement GREASE support
- [ ] Implment POC ECH enabled client
- [ ] Implement POC ECH enabled server
- [ ] Implement minimal testing of Client side api
- [ ] Implement minimal testing of Server side api

**Comment by vdukhovni** [comment]
Preliminary tweaks of the task breakdown done.

**Comment by sftcd** [comment]
@nhorman I'm not quite sure what "bite-size feature branch PRs" means, but am happy to help out as I can with getting that started and then done. (I might benefit from a voice chat with someone on that topic as you/we get to doing things.)

If each bite-size PR for a feature branch means (iterations of) adding a small chunk of the code from my implementation, then reviewing that and merging to the feature-branch, without an expectation that the feature-branch at all times does something useful, then that seems reasonable as a plan. If it means something else, then I'm less sure how doable it may be as not all useful chunks of code will be bite-sized.

That said, I do appreciate the attempt to break EPIC down into something more doable, I've been puzzled by how to get that done myself:-)

**Comment by vdukhovni** [comment]
You figured it out.  The feature branch is precisely for staging smaller incremental reviews, merge what's been reviewed, and repeat. It should be created soon.
