### ISSUE TITLE
High priority async bugfixing

### ISSUE THREAD

**Issue by nhorman** [openssl/project#596]
Long running epic for high priority (regression/urgent) issues as they arrive
```[tasklist]
### Tasks
- [ ] https://github.com/openssl/openssl/pull/24630
- [ ] https://github.com/openssl/private/issues/508
- [ ] https://github.com/openssl/openssl/issues/24739
- [ ] https://github.com/openssl/private/issues/506
- [ ] https://github.com/openssl/project/issues/682
- [ ] https://github.com/openssl/project/issues/680
- [ ] https://github.com/openssl/project/issues/681
- [ ] https://github.com/openssl/project/issues/676
- [ ] https://github.com/openssl/project/issues/674
- [ ] https://github.com/openssl/project/issues/678
- [ ] https://github.com/openssl/project/issues/677
- [ ] https://github.com/openssl/project/issues/746
- [ ] https://github.com/openssl/project/issues/747
- [ ] https://github.com/openssl/openssl/issues/24672
- [ ] https://github.com/openssl/project/issues/675
- [ ] https://github.com/openssl/project/issues/679
- [ ] https://github.com/openssl/private/issues/550
- [ ] https://github.com/openssl/project/issues/762
- [ ] https://github.com/openssl/openssl/issues/24908
- [ ] https://github.com/openssl/openssl/issues/24913
- [ ] https://github.com/openssl/openssl/issues/21645
- [ ] https://github.com/openssl/project/issues/798
- [ ] https://github.com/openssl/project/issues/799
- [ ] https://github.com/openssl/project/issues/800
- [ ] https://github.com/openssl/project/issues/821
- [ ] https://github.com/openssl/project/issues/831
```

**Comment by vavroch2010** [comment]
All done closing
