### ISSUE TITLE
3.5 Planning Epic

### ISSUE THREAD

**Issue by nhorman** [openssl/project#599]
This epic collects tasks to complete to prepare for 3.5 release themes and work

The output of this epic is a new project board that contain the epics/tasks/schedule/roadmap for 3.5
```[tasklist]
### Tasks
- [ ] https://github.com/openssl/project/issues/606
- [ ] https://github.com/openssl/project/issues/607
- [ ] https://github.com/openssl/project/issues/608
- [ ] Make a decision on future minor releases vs 4.0 release
```

**Comment by vavroch2010** [comment]
Closing will be handled differently
