### ISSUE TITLE
Create 3.5.0 project board to collect output of 3.5 planning

### ISSUE THREAD

**Issue by nhorman** [openssl/project#606]
In this task, we need to:

```[tasklist]
### Tasks
- [ ] clone the 3.4.0 project board to be our 3.5.0 project board
- [ ] Create tasks tracking dates/milestones for that release on a 6 month development cycle
- [ ] Present the board in a planning meeting to arrive at consensus for the planning dates
```
