### ISSUE TITLE
Solicit Business interests for goals in 3.5.0

### ISSUE THREAD

**Issue by nhorman** [openssl/project#607]
Note: This issues is dependent on #606 
This task requires the assignee to:

```[tasklist]
### Tasks
- [ ] Reach out to our premium customer base to solicit for features they may want
- [ ] Identify Features that seem to be commonly requested by our communities
- [ ] Create an Epic on the 3.5.0 project board embodying the request for group review and refinement
```
