### ISSUE TITLE
Solicit community for goals in 3.5.0

### ISSUE THREAD

**Issue by nhorman** [openssl/project#608]
Note: This issues is dependent on #606

```[tasklist]
### Tasks
- [ ] Review our public issues / Pull requests
- [ ] Identify frequently requested features
- [ ] Create Epics documenting those feature requests in the 3.5.0 planning board
```
