### ISSUE TITLE
Remove atexit registration from openssl

### ISSUE THREAD

**Issue by nhorman** [openssl/project#671]
Based on the abundance of reports, we need to remove atexit from openssl

```[tasklist]
### Tasks
- [ ] Announce to community that this is a major change in openssl, requiring cleanup
- [ ] Decide on an approach for removal of atexit(), and document impact to users
- [ ] Make PR to remove atexit handlers from openssl
```
