### ISSUE TITLE
Address Clusterfuzz NULL deref at unknown location

### ISSUE THREAD

**Issue by nhorman** [openssl/project#674]
We have a new clusterfuzz report:
https://oss-fuzz.com/testcase-detail/6568270206402560

Its a NULL deref on a read, with the pc pointing to zero.  Its rather odd case in that it looks like the program jumped to the NULL page, but asan is unable to provide a stack trace

However, the issue is marked as reliably reproducible, so it seems the tasks here are:

```[tasklist]
### Tasks
- [ ] Download the corpus locally
- [ ] Reproduce the failure on a local system
- [ ] Run it under a debugger to capture the failing location
- [ ] Identify the root cause of the issue
- [ ] Implement a fix
```
invest 1-3 days identifying the issue and open a PR to address it or create an issue to address it later

**Comment by Sashan** [comment]
It's a duplicate of #682
