### ISSUE TITLE
Address Clusterfuzz NULL deref at unknown location (again)

### ISSUE THREAD

**Issue by nhorman** [openssl/project#675]
We have a new clusterfuzz report:
https://oss-fuzz.com/testcase-detail/6568270206402560

Its a NULL deref on a read, with the pc pointing to zero.  Its rather odd case in that it looks like the program jumped to the NULL page, but asan is unable to provide a stack trace

However, the issue is marked as reliably reproducible, so it seems the tasks here are:

```[tasklist]
### Tasks
- [ ] Download the corpus locally
- [ ] Reproduce the failure on a local system
- [ ] Run it under a debugger to capture the failing location
- [ ] Identify the root cause of the issue
- [ ] Implement a fix
```

Note, This may be a duplicate of #674 , but oss-fuzz logged it separately, so I'm tracking it separately
invest 1-3 days identifying the issue and open a PR to address it or create an issue to address it later

**Comment by vdukhovni** [comment]
This issue appears to have been fixed per: https://oss-fuzz.com/testcase-detail/6568270206402560 via commits https://github.com/openssl/openssl/compare/06da14737369e7c90899aed4bb21cce9a0910d29...861e1f450c808bdf675bbf0d3e17303a3f16d06c
