### ISSUE TITLE
Address Clusterfuzz segfault in lcdim test

### ISSUE THREAD

**Issue by nhorman** [openssl/project#676]
We have a new clusterfuzz report:
https://oss-fuzz.com/testcase-detail/6281243442348032

Its a timeout issue in the lcdim fuzzer, on insert to a hash table.  specifically it looks like the timeout triggered while we in the bucket traversal list in the hashtables getrn function.

Given that its a timeout, my first suspicion would be that we're not limiting data size in the test and as a result are taking a large amount of time in the lcid_hash or lcid_cmp function, and the timeout just happens to trigger a few instructions farther on.  Either that or the hash bucket list has gotten corrupted somehow

```[tasklist]
### Tasks
- [ ] download the fuzzer corpus that reproduced the crash
- [ ] reproduce the problem locally
- [ ] identify the source of the excess latency on the lhash insert
- [ ] properly groom the fuzzer input data to avoid the issue 
```

Invest 1-3 day to understand the problem, and either create a PR to fix it or open an issue to create the work

**Comment by mattcaswell** [comment]
Fixed in openssl/openssl#24831
