### ISSUE TITLE
Address clusterfuzz timeout in quic-srtm

### ISSUE THREAD

**Issue by nhorman** [openssl/project#679]
We have a new clusterfuzz timeout:
https://oss-fuzz.com/testcase-detail/5618331942977536

its in quic-srtm, simmilar to the lcidm issue in #676 , only here we're timing out in the doall iterator, so it may just be that we have loaded up the srtm hash table with too many entries.  I would be willing to bet that if cmd statistically results in a high amount of CMD_ADD operations, the table probably grows very large

```[tasklist]
### Tasks
- [ ] download the reproducer corpus
- [ ] reproduce and confirm the issue
- [ ] Assuming the above is confirmed, insert a limit on the number of srtm entries that we can hold, and confirm the problem is resolved
```
