### ISSUE TITLE
Write additional fault injection tests for QUIC server

### ISSUE THREAD

**Issue by nhorman** [openssl/project#716]
Write additional fault injection tests to cover QUIC server functionality

We should, during refinement, potentially break this into several subtasks, to increase parallelism
```[tasklist]
### Tasks
- [ ] https://github.com/openssl/project/issues/726
```

**Comment by nhorman** [comment]
currently, we have the following tests for quic:

- quic_wire_test
- quic_txp_test
- quic_txpim_test
- quic_stream_test
- quic_srtm_test
- quic_srt_gen_test
- quic_record_test
- quic_rcidm_test
- quic_qlog_test
- quic_newcid_test
- quic_multistream_test
- quic_lcidm_test
- quic_fifd_test
- quic_fc_test
- quicfaulttest
- quic_cfq_test
- quic_cc_test
- quicapitest
- quic_ackm_test
- buildtest_c_quic
- quic_client_test
- quic_tserver_test

Within that list, all but the last 2 item test code that is common to both client and server code, so our coverage is reasonably good in terms of unit testing
the quic_tserver_test creates a 'dummy' server using internal api calls, so doesn't really address our server testing goals I think.

If our goal is to exercise our quic client and quic server in what might approximate 'real world' usage, I would suggest the best approach is to augment our quic interop testing such that we:

- [x] create an hq-interop-server (a companion to our quic-hq-interop client in the demos/guide directory
- [x] augment our interop container in tests/quic-openssl-docker, to run the server as part of our interop ci.

**Comment by vavroch2010** [comment]
This activity is handled elsewhere
