### ISSUE TITLE
Develop a blocking quic server to use for the writing of a guide

### ISSUE THREAD

**Issue by nhorman** [openssl/project#722]
Simmilar to demos/guide/tls-server-block.c, we need a quic-server-block application

Note, this is just a task for writing the code, not the documentation

```[tasklist]
### Tasks
- [x] Review tls-server-block
- [x] Review quic-client-block
- [x] Implement a quic-server-block application that uses the quic api to respond to quic connections
```
