### ISSUE TITLE
[Epic] Performance measurement infrastructure

### ISSUE THREAD

**Issue by quarckster** [openssl/project#790]
This epic tracks tasks required to build performance measurement infrastructure. As measurement data, we take the output of performance testing applications from  <https://github.com/openssl/tools/tree/master/perf>. The testing applications should run on a matrix of various platforms and openssl library versions:

- Ubuntu Server 20.04 x86_64, Debian 11 x86, FreeBSD 13.0 x86_64, Windows 10 x86_64, Windows 10 x86, MacOS 11 x86_64, MacOS 11 M1
- 3.0, 3.1, 3.2, 3.3, master
 
Test output will be submitted to a database and represented on Grafana graphs at https://openssl-library.org/performance.html
```[tasklist]
### Tasks
- [ ] https://github.com/openssl/project/issues/791
- [ ] https://github.com/openssl/project/issues/792
- [ ] https://github.com/openssl/project/issues/793
- [ ] https://github.com/openssl/private/issues/585
- [ ] https://github.com/openssl/project/issues/794
- [ ] https://github.com/openssl/project/issues/795
- [ ] https://github.com/openssl/project/issues/796
- [ ] https://github.com/openssl/project/issues/822
- [ ] https://github.com/openssl/project/issues/832
- [ ] https://github.com/openssl/project/issues/833
```

**Comment by quarckster** [comment]
This Epic is done.
