### ISSUE TITLE
Feature: Produce windows installer binaries as release artifacts

### ISSUE THREAD

**Issue by nhorman** [openssl/project#875]
3.4 debuted a new repository to allow customers to build their own windows installer for openssl in a consistent fashion.

The goal for 3.5 is to use that repository to produce our own windows binary installer and include it as a binary artifact in our release process

```[tasklist]
### Tasks
- [x] Investigate legalities of distributing binaries as part of our release
- [ ] Obtain a certificate from Microsoft/Verisign to sign our installer
- [ ] Obtain and deploy an HSM to preform signing of the installer for us
- [ ] Update our manual build github action to include a signing request to the HSM to produce signed binaries
- [ ] Integrate our github build action into our release process
```
