### ISSUE TITLE
Community Reported Issue Work

### ISSUE THREAD

**Issue by nhorman** [openssl/project#879]
Tracks incidental community supported issues that we  have committed to addressing
```[tasklist]
### Tasks
- [ ] https://github.com/openssl/openssl/issues/22660
- [ ] https://github.com/openssl/openssl/issues/25509
- [ ] https://github.com/openssl/openssl/issues/25516
```
