### ISSUE TITLE
Community Assistance: DTLS1.3 review for 3.5 merge

### ISSUE THREAD

**Issue by nhorman** [openssl/project#893]
There is an ongoing community effort to implement DTLS1.3, which we would potentially like to target for 3.5.  While this is not a commitment, it is an "as time allows effort" that includes the following tasks

To accomplish this We need to complete the following tasks
```[tasklist]
### Tasks
- [ ] https://github.com/openssl/project/issues/479
- [ ] https://github.com/openssl/project/issues/616
- [ ] https://github.com/openssl/project/issues/615
- [ ] https://github.com/openssl/project/issues/617
- [ ] https://github.com/openssl/project/issues/618
- [ ] https://github.com/openssl/project/issues/610
- [ ] https://github.com/openssl/project/issues/609
- [ ] https://github.com/openssl/project/issues/619
- [ ] https://github.com/openssl/project/issues/620
- [ ] https://github.com/openssl/project/issues/611
- [ ] https://github.com/openssl/project/issues/612
- [ ] https://github.com/openssl/project/issues/613
- [ ] https://github.com/openssl/project/issues/614
- [ ] https://github.com/openssl/project/issues/621
- [ ] https://github.com/openssl/project/issues/622
- [ ] https://github.com/openssl/project/issues/623
- [ ] https://github.com/openssl/project/issues/624
- [ ] https://github.com/openssl/project/issues/626
- [ ] https://github.com/openssl/project/issues/627
- [ ] https://github.com/openssl/project/issues/628
- [ ] https://github.com/openssl/project/issues/629
- [ ] https://github.com/openssl/project/issues/630
- [ ] https://github.com/openssl/project/issues/631
- [ ] Review above tasks and determine if DTLS1.3 is ready for merge, if so, create epic in 3.5 project board to complete any remaining changes and merge the work
- [ ] https://github.com/openssl/project/issues/660
- [ ] https://github.com/openssl/project/issues/661
- [ ] https://github.com/openssl/project/issues/662
- [ ] https://github.com/openssl/project/issues/663
- [ ] https://github.com/openssl/project/issues/668
- [ ] Gap analysis of DTLS1.3 - Determine missing functionality from the in-existance PR's
- [ ] Identify needed modifications to test infrastructure to Test DTLS 1.3
- [ ] Write up a presentation document outlining how DTLS 1.3  works in openssl
- [ ] https://github.com/openssl/private/issues/588
- [ ] https://github.com/openssl/project/issues/863
- [ ] https://github.com/openssl/project/issues/808
- [ ] Review https://github.com/openssl/openssl/pull/25668
```

**Comment by nhorman** [comment]
action: reach out to Fredrick to get updated list of prs

**Comment by t8m** [comment]
No longer relevant.
