### ISSUE TITLE
Add quic server interoperability testing for quic-server branch

### ISSUE THREAD

**Issue by nhorman** [openssl/project#919]
In order to better evaluate the readiness of our quic-server support, we should augment our quic-interop CI job such that we run the tests with openssl as a quic server.  This involves

```[tasklist]
### Tasks
- [ ] https://github.com/openssl/project/issues/922
- [x] Either augment our quic-openssl-docker container to build from our quic-server branch , or create a separate quic server container, such that quic-server support is available for testing
- [x] Augment the run_endpoint.sh script in test/quic-openssl-docker to support server operation
- [ ] Augment the interop CI job for quic to specify quic as the server with every other supported client
```
