### ISSUE TITLE
PQ Forward Looking work container

### ISSUE THREAD

**Issue by nhorman** [openssl/project#996]
@baentsch as requested here is a tracking epic for you to plan future PQ work.  As you can see below, it contains the existing work that we have planned for 3.5.  Please feel free to add any issues here that you believe represent future work for the PQ effort.  Note that Issues which you add here will not immediately be scheduled for a given release.  As time/resources allow, we can move work from this list to a specific PQ epic scheduled for a specific release.  Note that the 3.5 PQ epic is listed below to be inclusive of all the work we are doing.  Please feel free to append to this list as you see fit

```[tasklist]
### Tasks
- [ ] https://github.com/openssl/project/issues/999
```

```[tasklist]
### Tasks
- [ ] https://github.com/openssl/private/issues/675
- [ ] https://github.com/openssl/private/issues/674
- [ ] https://github.com/openssl/private/issues/670
- [ ] https://github.com/openssl/project/issues/1044
- [ ] https://github.com/openssl/private/issues/669
- [ ] https://github.com/openssl/project/issues/1039
- [ ] https://github.com/openssl/project/issues/1038
- [ ] https://github.com/openssl/project/issues/1042
- [ ] https://github.com/openssl/project/issues/1049
- [ ] https://github.com/openssl/private/issues/683
- [ ] https://github.com/openssl/private/issues/681
- [ ] https://github.com/openssl/private/issues/687
- [ ] https://github.com/openssl/private/issues/677
- [ ] https://github.com/openssl/temporary/issues/11
- [ ] https://github.com/openssl/private/issues/685
- [ ] https://github.com/openssl/project/issues/1036
- [ ] https://github.com/openssl/project/issues/1048
- [ ] https://github.com/openssl/project/issues/1041
- [ ] https://github.com/openssl/private/issues/673
- [ ] https://github.com/openssl/private/issues/672
- [ ] https://github.com/openssl/project/issues/1040
```

**Comment by mattcaswell** [comment]
@baentsch I would put ML-DSA above SLH-DSA in terms of priority in the above list, e.g. perhaps in this order??

ML-DSA
SLH-DSA
MLKEM-1024
MLKEM-512

IIUC, @slontis is already working on SLH-DSA though

**Comment by baentsch** [comment]
> @slontis is already working on SLH-DSA though

Perfect! Just the native part/port as per https://github.com/openssl/private/issues/675 or also the provider piece as per https://github.com/openssl/private/issues/683?

**Comment by mattcaswell** [comment]
> Perfect! Just the native part/port as per https://github.com/openssl/private/issues/675 or also the provider piece as per https://github.com/openssl/private/issues/683?

I believe he is doing all of it. Although I think he has implemented it from scratch, rather than porting the BoringSSL implementation.

**Comment by baentsch** [comment]
Just closed all SLH-DSA related issues as https://github.com/openssl/openssl/pull/25882 looks excellent.
