### ISSUE TITLE
Verify the correctness ML-KEM768

### ISSUE THREAD

**Issue by nhorman** [openssl/project#997]
Need to validate the correctness and behavior of the ported boringssl code in openssl:
```[tasklist]
### Tasks
- [ ] https://github.com/openssl/private/issues/715
- [ ] openssl/project#1047
- [ ] https://github.com/openssl/private/issues/718
- [ ] https://github.com/openssl/project/issues/994
- [ ] https://github.com/openssl/project/issues/993
- [ ] https://github.com/openssl/project/issues/992
- [ ] https://github.com/openssl/private/issues/722
- [ ] https://github.com/openssl/private/issues/723
```
All of these tests to be done for ML-KEM768 for starters. Everything to be repeated as and when MLKEM1024 and MLKEM512 are getting added (TBD when this is the case/needed).

**Comment by baentsch** [comment]
Tagging @vdukhovni : This is the most pertinent issue that could benefit from your expertise -- and make your proposed review of what's now landed in the feature branch _very_ valuable indeed.

**Comment by baentsch** [comment]
Tagging @vavroch2010 : Why is this not visible in https://github.com/orgs/openssl/projects/20/views/1 or any backlog? This is the probably the most relevant issue to be discussed/resolved now...
